-- Add FK columns
ALTER TABLE members ADD COLUMN IF NOT EXISTS country_id INTEGER REFERENCES countries(id) ON DELETE SET NULL;
ALTER TABLE members ADD COLUMN IF NOT EXISTS division_id INTEGER REFERENCES divisions(id) ON DELETE SET NULL;
ALTER TABLE members ADD COLUMN IF NOT EXISTS district_id INTEGER REFERENCES districts(id) ON DELETE SET NULL;
ALTER TABLE members ADD COLUMN IF NOT EXISTS upazila_id INTEGER REFERENCES upazilas(id) ON DELETE SET NULL;
ALTER TABLE members ADD COLUMN IF NOT EXISTS union_id INTEGER REFERENCES unions(id) ON DELETE SET NULL;
ALTER TABLE members ADD COLUMN IF NOT EXISTS village_id INTEGER REFERENCES villages(id) ON DELETE SET NULL;

-- Note: home_id was added in previous migration

-- Drop text columns
ALTER TABLE members DROP COLUMN IF EXISTS country;
ALTER TABLE members DROP COLUMN IF EXISTS division;
ALTER TABLE members DROP COLUMN IF EXISTS district;
ALTER TABLE members DROP COLUMN IF EXISTS upazila;
ALTER TABLE members DROP COLUMN IF EXISTS union_ward;
ALTER TABLE members DROP COLUMN IF EXISTS village;
ALTER TABLE members DROP COLUMN IF EXISTS home_name;
